version: '3.8'
services:
  django:
    container_name: django
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app
      - static_files:/app/static
      - ./app/static:/app/static
    expose:
      - 8000
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_ARBITRARY: ${PMA_ARBITRARY}
    ports:
      - "8080:80"

  nginx:
    container_name: nginx
    build: ./nginx
    environment:
      NGINX_HOST: localhost
      NGINX_PORT: 80
    volumes:
      - static_files:/etc/nginx/back/static
      - ./front/build:/etc/nginx/front
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django

  front:
    container_name: front
    build: ./front
    volumes:
      - ./front:/etc/front


volumes:
  static_files:
