version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  outlne:
    container_name: outline
    build:
      context: ./src
    env_file:
      - .env
    ports:
      - "8000:8000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
