version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  outline:
    container_name: outline
    restart: always
    build:
      context: ./src
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/usr/src
    ports:
      - "8000:8000"

  telegram-bot:
    container_name: telegram-bot
    restart: always
    build:
      context: ./src
      dockerfile: ./Dockerfile.bot
    env_file:
      - .env
    volumes:
      - ./src:/usr/src

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
