version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  outline:
    container_name: outline
    build:
      context: ./src
    env_file:
      - .env
    volumes:
      - ./src:/usr/src
    ports:
      - "8000:8000"

  telegram_bot:
    container_name: telegram_bot
    build:
      context: ./src/bot
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
